### ISSUE TITLE
Use XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by FatBoyXPC** [jfly/shtuff#3]
[This article](https://medium.com/@jdxcode/12-factor-cli-apps-dd3c227a0e46) makes a great point about following XDG, and we totally should! We were torn about the directory earlier, and this should be a simple enough change!

Edit: It appears that mac does not have this!

**Comment by jfly** [comment]
I agree that `$XDG_RUNTIME_DIR` seems like the right place for us! The XDG spec says:

> If $XDG_RUNTIME_DIR is not set applications should fall back to a replacement directory with similar capabilities and print a warning message. Applications should use this directory for communication and synchronization purposes and should not place larger files in it, since it might reside in runtime memory and cannot necessarily be swapped out to disk.

Printing a warning message feels bit annoying if all mac users don't have this env var set, but it's a "should", so we could get away with not doing it if we want.

According to https://serverfault.com/a/391960 and https://lists.macports.org/pipermail/macports-users/2015-November/040037.html, it sounds like a subdirectory in `python3 -c "import tempfile; print(tempfile.gettempdir())"` is an ok fallback.

**Comment by jfly** [comment]
Ooh, looks like there's a python library for this! See https://pypi.org/project/pyxdg/ (documentation https://pyxdg.readthedocs.io/en/latest/basedirectory.html#data-directories)

```
➜  ~ python3 -c "import xdg.BaseDirectory; print(xdg.BaseDirectory.save_data_path('shtuff'))"
/home/jeremy/.local/share/shtuff
```

(this is not to be confused with https://pypi.org/project/xdg/, which might also do what we want, but I already had `pyxdg` installed on my system)

So, next step: figure out if `pyxdg` works on a mac, and if that `save_data_path` method works over there!

**Comment by jfly** [comment]
Got @ddzoan to try this out on his Mac. Looking good!

```python
>>> import xdg.BaseDirectory; print(xdg.BaseDirectory.save_data_path('shtuff'))
/Users/ddzoan/.local/share/shtuff
```
